In [2]:
import pandas as pd

In [11]:
# 读取数据
df_sales = pd.read_csv('Project_Data/sales_data.csv', encoding='UTF-8')

# 限制数据读取的列
df_students = pd.read_csv('Project_Data/student_data.csv',
                          encoding = 'UTF-8',
                          usecols = ['姓名', '语文', '数学','英语'])

In [7]:
df_students

   姓名  语文  数学  英语
0  赵一  92  85  88
1  钱二  78  90  82
2  孙三  88  76  91
3  李四  65  82  70
4  周五  95  91  93
5  吴六  72  68  75
6  郑七  80  85  78
7  王八  58  70  65
8  冯九  90  88  94
9  陈十  85  79  82

In [8]:
df_sales

            日期   产品  地区 销售员  数量    总价
0   2026-01-05  笔记本  华东  张伟  10  4500
1   2026-01-07   鼠标  华南  李娜  50    89
2   2026-01-12   键盘  华北  王强  30   280
3   2026-01-15  显示器  华东  张伟   8  3200
4   2026-01-20  笔记本  华南  李娜  15  4600
5   2026-01-22   鼠标  华北  王强  60    85
6   2026-02-02   键盘  华东  张伟  25   275
7   2026-02-10  显示器  华南  李娜   5  3300
8   2026-02-14  笔记本  华北  王强  12  4700
9   2026-02-18   鼠标  华东  张伟  45    90
10  2026-02-25   键盘  华南  李娜  35   290
11  2026-03-01  显示器  华北  王强   6  3250

In [10]:
df_sales_1 = pd.read_csv('Project_Data/sales_data.csv',
                         encoding = 'UTF-8',
                         usecols = ['产品', '数量', '单价'])

In [12]:
# 数据处理
df_sales['销售金额'] = df_sales['数量'] * df_sales['单价']

# 写入数据
df_sales.to_csv('Project_Data/sales_data_2.csv', encoding = 'UTF-8', index = False)